# site properties and page defaults
title: The Bowen Lab
subtitle: 
description: We're a neuroscience lab at the University of Washington that studies how the brain builds predictions to help support homeostasis.    
header: images/background.png
footer: images/background.png
proofer: false

# cross-site linkage
sameAs:
  - https://orcid.org/0000-0002-8911-2572
  - https://scholar.google.com/citations?user=EmnJRuwAAAAJ&hl=en
  - https://github.com/thebowenlab
  - https://www.hhmi.org/scientists/anna-bowen
  # - https://your-uw-profile-url

# domain
url: https://thebowenlab.org
baseurl: ""

# site social media and other links
links:
  orcid: 0000-0002-8911-2572
  google-scholar: EmnJRuwAAAAJ&hl=en
  github: thebowenlab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
