# should be a list of dicts, with format 
#- id:
#  type:
#  image:

- id: https://doi.org/10.7554/eLife.84604
  description: Examines the distribution of value-coding neurons across prefrontal cortex, combining electrophysiology and 2-photon calcium imaging. Dataset available for download.
  date: 2023-05-30
  image: images/citations/ottenheimer_2023.png
  buttons:
    - type: source
      text: Manuscript Source
      link: https://elifesciences.org/articles/84604
    - type: data
      text: download data
      link: https://doi.org/10.6084/m9.figshare.21365598
  tags:
    - open science
    - collaboration
  repo: steinmetzlab/ottenheimer-et-al-2022

- id: https://doi.org/10.1038/s41467-023-36603-z
  image: images/citations/arthurs_2023.webp
  tags:
    - collaboration

- id: https://doi.org/10.1101/2025.02.04.636286
  image: images/citations/neuropixelsopto_2025.png
  tags:
    - collaboration
    - preprint

- id: https://doi.org/10.1101/2024.11.01.621418
  image: images/citations/matveev_2025.png
  tags: 
    - preprint

- id: https://doi.org/10.1126/sciadv.adp3059
  image: images/citations/ottenheimer_2025.jpg
  tags:
    - collaboration

- id: https://doi.org/10.7554/eLife.59799
  image: images/citations/bowen_2020.jpg
  description: Parsed the network downstream of parabrachial CGRP neurons and how activity is added to give rise to distinct physiological and behavioral states and learning.
  buttons:
    - type: data
      text: download data
      link: https://doi.org/10.5061/dryad.rn8pk0p7k
  tags:
    - open science

- id: https://doi.org/10.1038/s41467-023-35826-4
  description: Identified topographic differences in coding of current external versus internal threats in central amygdala CGRP-receptor expressing neurons.
  image: images/citations/bowen_2023.webp
  buttons:
    - type: data
      text: download data
      link: https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-023-35826-4/MediaObjects/41467_2023_35826_MOESM4_ESM.xlsx
    
- id: https://doi.org/10.1523/jneurosci.1162-19.2019
  image: images/citations/jneuro_review.jpg
  tags:
    - review

- id: https://doi.org/10.1073/pnas.2004941117

- id: https://doi.org/10.1038/nature25511
  image: images/citations/campos_2018.webp
  description: Revealed unified activation of parabrachial CGRP neurons by multi-modal threats, including somatic pain, itch, visceral malaise -- in addition to satiety and conditioned fear.

- id: https://doi.org/10.1038/nn.4574
  image: images/citations/campos_2017.webp

#- id: https://doi.org/10.1016/j.cmet.2016.04.006
 
  


   
  
