# should be a list of dicts, with format 
#- id:
#  type:
#  image:

- id: https://doi.org/10.7554/eLife.84604
  type: paper
  description: Examines the distribution of value-coding neurons across prefrontal cortex, combining electrophysiology and 2-photon calcium imaging. Dataset available for download. 
  date: 2023-05-30
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: source
      text: Manuscript Source
      link: https://elifesciences.org/articles/84604
    - type: data
      link: https://doi.org/10.6084/m9.figshare.21365598
  tags:
    - open science
    - collaboration
  repo: steinmetzlab/ottenheimer-et-al-2022

- id: https://doi.org/10.1038/s41467-023-36603-z
  type: paper
  tags:
    - collaboration

- id: https://doi.org/10.1101/2025.02.04.636286
  type: paper
  tags:
    - collaboration
    - preprint

- id: https://doi:10.1126/sciadv.adp3059
  type: paper
  tags:
    - collaboration

- id: https://doi:10.1038/s41467-023-35826-4
  type: paper
  description: Identified topographic differences in coding of current external versus internal threats in central amygdala CGRP-receptor expressing neurons. 
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-023-35826-4/MediaObjects/41467_2023_35826_Fig1_HTML.png?as=webp

-id: https://doi:10.1523/jneurosci.1162-19.2019
  type: review
  tags:
    - review
  
