- id: https://doi.org/10.7554/eLife.84604.3
  type: paper
  description: Examines the distribution of value-coding neurons across prefrontal cortex, commbining electrophysiology and 2-photon calcium imaging. Dataset available for download. 
  date: 2023-05-30
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: source
      text: Manuscript Source
      link: https://elifesciences.org/articles/84604#fig1s2
    - type: data
      link: https://doi.org/10.6084/m9.figshare.21365598
  tags:
    - open science
    - collaboration
  repo: steinmetzlab/ottenheimer-et-al-2022
